resources/views/dashboard.blade.php

This PR disable the Devmode by using the minified VueJS Version as mentioned in the docs:
https://vuejs.org/v2/guide/installation.html#CDN

Use minified VueJS CDN Version

---

config/websockets.php
resources/views/dashboard.blade.php
src/Apps/App.php
src/Apps/ConfigAppProvider.php

This PR fixes https://github.com/beyondcode/laravel-websockets/issues/12
It is now possible to easily configure the server, which the dashboard connects to.
My setup is the following:
I have one server (the webserver) which is hosting the dashboard: dev.my.app
The socket server is running under ws-dev.my.app 
Without this PR, the dashboard tries to conntect to dev.my.app because, in the connect section `window.location.hostname` is used. This behavior is after this pr still the same, except someone fills the new 'server' configuration variable. Then this value will be used.

Add optional server variable 

---

src/Server/HttpServer.php
src/Statistics/Events/StatisticsUpdated.php
tests/Channels/ChannelTest.php
tests/Channels/PresenceChannelTest.php
tests/Channels/PrivateChannelTest.php
tests/Messages/PusherClientMessageTest.php

Some classes had namespace issues and it looks like the reason we're seeing the error referred in #10 is due to the namespace being wrong here and when it tries to call, it breaks.
I ran a few tests and the `StatisticsUpdated` job is running fine now (Been testing for the last few hours now, no issues).

Fix Namespace

---

src/HttpApi/Controllers/FetchChannelsController.php
tests/HttpApi/FetchChannelsTest.php

^ without warnings are thrown if there are no channels (or the filtered query once it works returns no channels) because it expects `{"channels": {}}` instead of php encoding empty arrays as `{"channels": []}`.

Fix Pusher lib expecting empty object not array

---

config/websockets.php
src/Console/StartWebSocketServer.php

Without this the statistics requests will never reach the server if it's not available on 127.0.0.1 directly (think load balanced or distributed services). 
Let the system supply a DNS resolver or use Cloudflare's 1.1.1.1 as an default.

Use an actual DNS resolver

---

CHANGELOG.md
resources/views/dashboard.blade.php
src/Dashboard/Http/Controllers/AuthenticateDashboard.php
src/WebSocketsServiceProvider.php

This PR fixes the problem with #23.

Fix Invalid Signature issue and enable event creator to be sent from any app

---

src/HttpApi/Controllers/Controller.php
tests/HttpApi/FetchChannelTest.php
tests/HttpApi/FetchChannelsTest.php
tests/HttpApi/FetchUsersTest.php

I noticed that running this request to the websocket server yields an invalid signature error.
```php
$pusher->get_channels(['filter_by_prefix' => 'presence-global']);
```
I noticed that the signatures are not generated as the Pusher lib and server expects/validates them.
So I fixed that and modified all tests to use the correct way (according to the `Pusher` library).
----
Edit: After more testing this is broken since the route parameters are added as query params causing it to mess up the signature creation...
----
Edit edit: This now works like it should and ready for review

Fix signature validation

---

composer.json
src/HttpApi/Controllers/Controller.php
src/HttpApi/Controllers/FetchChannelsController.php
src/Statistics/Events/StatisticsUpdated.php
src/WebSockets/Channels/Channel.php
src/WebSockets/Channels/ChannelManagers/ArrayChannelManager.php
src/WebSockets/Messages/PusherChannelProtocolMessage.php
src/WebSockets/Messages/PusherClientMessage.php
src/WebSockets/Messages/PusherMessageFactory.php
tests/ClientProviders/ConfigAppProviderTest.php
tests/Commands/CleanStatisticsTest.php
tests/TestCase.php

- Added support for `5.8.*` illuminate dependencies.
- Added support for `3.8.*` orchestra/testbench dependency
- ~NOTE: I needed to add `orchestra/testbench-core` as a dependency for now because a release wasn't tagged yet. See https://github.com/orchestral/testbench-core/issues/21. That line can be removed as soon as a release is tagged.~ This change is no longer needed, release was tagged.
- Add `: void` on test `setUp()` due to it being required by orchestra/testbench 3.8 (PHPUnit 8 compatibility change)
- Removed deprecated `array_` and `str_` global helpers (~I think I got them all, but I'm not 100% sure~ Thanks Scrutinizer for telling me the ones I missed! :tada:)
Fixes #119

Add support for Laravel 5.8

---

src/HttpApi/Controllers/FetchChannelsController.php
tests/HttpApi/FetchChannelsTest.php

Fixes #149
Currently, we can only get presence channels, because there is a filter in code:
https://github.com/beyondcode/laravel-websockets/blob/1c2b89b54d8d9d1c796b8391e41207da2a2f2423/src/HttpApi/Controllers/FetchChannelsController.php#L14-L16
But according to Pusher API documentation, there is no limitations needed, and presence channels should be filtered using `filter_by_prefix=presence-`:
https://pusher.com/docs/rest_api#method-get-channels
In this pull request, I implemented correct behavior for this endpoint:
- List with all channels now returned
- Attribute `user_count` must be requested via `info` query param
- Error code `400` will be returned if `user_count` is requested, and the request is not limited to presence channels

Fixed channels HTTP API endpoint

---

composer.json

Running the test suite locally did not show any problems (all 44 tests have passed).
```sh
PHPUnit 7.5.13 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.3.3
Configuration: /Users/tomdewit/Packages/laravel-websockets/phpunit.xml.dist
Error:         No code coverage driver is available
............................................                      44 / 44 (100%)
Time: 772 ms, Memory: 22.00 MB
OK (44 tests, 96 assertions)
```

Allow the use of pusher-php-server 4.0

---

composer.json

The resolverinterface (used in #223)  was newly introduced in reach/dns 1.1. This PR to avoid that people who are on react/dns 1.0 get issues.

update react dns to v1.1

---

resources/views/dashboard.blade.php

Debug dashboard will now show error message for maximum connection limit exceeded for a single app instead of showing nothing.

Debug dashboard connection exceeded error added

---

composer.json

Fix compatibility with laravel/passport

---

docs/basic-usage/pusher.md
docs/basic-usage/ssl.md

After pusher-js v6 the `encrypted` attribute was removed in favor of `forceTLS` and it is true by default, so we need to use `forceTLS: false`, to keep it working in local or when TLS is not enabled yet.
It is normally evidenced as a CORS issue when connecting to Laravel WebSockets.

Required changes after pusher-js v6

---

docs/faq/scaling.md

Just a fix for a broken link that I encountered while perusing the documentation on [beyondco.de](https://beyondco.de).

Fix broken link in FAQ

---

config/websockets.php
src/Statistics/Logger/HttpStatisticsLogger.php

Fixes #114
I didn't add any tests, I'm unclear on how would be best to test this.
Needs documentation added, probably around here: https://github.com/beyondcode/docs.beyondco.de/blob/master/resources/docs/laravel-websockets/1.0/debugging/dashboard.md

Add support for overriding stats logger's base URL

---

resources/views/dashboard.blade.php

Fix 404 url by adding Request getBasePath

---

config/websockets.php
src/Console/StartWebSocketServer.php

Comes in help for this: https://github.com/beyondcode/laravel-websockets/pull/115

[feature] Custom HttpStatisticsLogger instance

---

src/Console/RestartWebSocketServer.php
src/Console/StartWebSocketServer.php
src/WebSocketsServiceProvider.php
tests/Commands/RestartWebSocketServerTest.php

This PR adds a console command for restart the WebSocket server.
For example if you deploy with Laravel Envoyer the server should be restarted because of a new version of the WebSocket package.
The command is inspired by the queue restart command.
Please note that this only works if the server is automatically restarted by Supervisor or something else as the server is only stopped with this command.

[feature] Add restart command for WebSocket server

---

config/websockets.php
src/Console/StartWebSocketServer.php
src/WebSocketsServiceProvider.php

The config changes are not included in the `1.x` version and the purpose is to make it cleaner, group related configuration under the same keys and add proper comments.

[2.x] Config Changes

---

src/WebSockets/Channels/PresenceChannel.php
tests/Channels/PresenceChannelTest.php

[fix] Allow missing user_info on Presence channels

---

src/WebSocketsServiceProvider.php

Added exception handling for QueryException which is raised when no DB is present and Schema check is called due to which exception is seen when attempting composer update when no DB connection is available, often for CI with no DB at start it breaks.

Schema check breaks

---

.editorconfig
config/websockets.php
resources/views/dashboard.blade.php
src/Dashboard/DashboardLogger.php
src/Dashboard/Http/Controllers/ShowDashboard.php
src/Facades/StatisticsLogger.php
src/HttpApi/Controllers/TriggerEventController.php
src/PubSub/Drivers/LocalClient.php
src/PubSub/Drivers/RedisClient.php
src/Statistics/Logger/NullStatisticsLogger.php
src/WebSockets/Channels/Channel.php
src/WebSockets/Messages/PusherClientMessage.php
src/WebSockets/WebSocketHandler.php

This PR refactors the dashboard side. From design to how the Dashboard Logger is registering the events throughout the WebSockets server. It also adds a `NullStatisticsLogger` that will void any incoming statistics in case no statistics are needed.

[2.x] Refactoring dashboard

---

config/websockets.php
docs/debugging/dashboard.md
src/Console/CleanStatistics.php
src/Statistics/Drivers/DatabaseDriver.php
src/Statistics/Drivers/StatisticsDriver.php
src/Statistics/Events/StatisticsUpdated.php
src/Statistics/Http/Controllers/WebSocketStatisticsEntriesController.php
src/WebSocketsServiceProvider.php

Currently, you can use only the database (through the model) for the statistics storage. This can be quite unpleasant as MySQL is not so good as a time-series database when it comes to huge data ingestion. You might want to save them somewhere else, like Elasticsearch or InfluxDB.
To fix this, you may now define your own statistics driver that can store/delete data with any kind of database, leaving this customization to the user implementation. You can ingest the record and use it to build the statistic payload, or you can statically create new records or delete records.
For example, this is how the database driver looks:
```php
class DatabaseDriver implements StatisticsDriver
{
/**
* The model that controls the database table.
*
* @var …
```

[2.x] Custom statistics drivers

---

src/Server/Logger/WebsocketsLogger.php

When multiple routes are declared and WebSocket logger is enabled, all the routes will use the controller of the last route declared
This fixes the issue

Fix multiple routes not working when Logger enabled beyondcode#412

---

config/websockets.php

Just adding the ability to configure some more of the new configuration variables via ENV variables.

Add some extra ENV variables for the config file

---

docs/basic-usage/ssl.md

Caddy v2 greatly simplifies things for proxying websockets. The dumb rewrite hack is no longer necessary because request matchers handle it perfectly.
Caddy is _by far_ the simplest and easiest solution for proxying websockets like this.

Update Caddy example for Caddy v2

---

src/Apps/App.php
src/Apps/AppManager.php
src/Apps/ConfigAppManager.php

Frankly, I don't understand why the typing was removed from these methods in https://github.com/beyondcode/laravel-websockets/pull/471, seems like a strange decision. `mixed` is almost never the right thing to use.

Fix docblocks in App

---

composer.json
src/ChannelManagers/LocalChannelManager.php
src/ChannelManagers/RedisChannelManager.php
src/Console/Commands/StartServer.php
src/Contracts/ChannelManager.php
src/Helpers.php
src/Server/Messages/PusherChannelProtocolMessage.php
src/Server/MockableConnection.php
src/Server/WebSocketHandler.php
src/Statistics/Collectors/RedisCollector.php
tests/Commands/StartServerTest.php
tests/ConnectionTest.php
tests/Mocks/Connection.php
tests/PresenceChannelTest.php
tests/PrivateChannelTest.php
tests/PublicChannelTest.php
tests/ReplicationTest.php

Since the horizontal replication stores some of the presence channels data and the connection IDs in Redis, if the server abruptly closes, the Redis data might still be persistent.
In this PR, I came up with a first gate on which upon SIGINT/SIGTERM, the entire connections list gets closed, but not before the server marks itself as being unable to accept new connections, while the current connections are closed and the process finally terminates.
This is definitely not ideal but as the first gate on termination protection, it should be enough until I come up with another idea on how to expire the data within the Redis sets between ping-pongs (so if the user doesn't ping anymore, it will let the Redis DB invalidate the key associated to that connection).
Additionally, since whenever one …

[feature] PCNTL signals into soft-close of connections for Redis horizontal replication

---

src/WebSockets/Channels/PresenceChannel.php
tests/Channels/PresenceChannelTest.php

I know 2.x is under way but it would be nice to have 1.x in a working state and this is quite the bug 😄 
**What is happening?**
Presence channels are double counting unique users because it's counting socket ID's.
**How does Pusher handle this?**
Pusher uses the `user_id` property to uniquely count the users in a presence channel.
**Does this PR fix that?**
Well, yes 😉 
**Okay, so why are the tests failing?**
See: #528.
Would be great to see this released on 1.x.

Fix presence channels double counting users

---

.github/workflows/run-tests.yml

Do not test Laravel 8 on PHP 7.2.
Master is now failing including any new PR because Laravel 8 requires PHP 7.3+.
As a bonus I removed some PHP extension that are not needed to run the testsuite speeding up the suite a bit.

Fix test suite

---

resources/views/dashboard.blade.php
src/Dashboard/Http/Controllers/SendMessage.php
tests/Dashboard/SendMessageTest.php

[fix] Dashboard cannot initialize the channel manager

---

resources/views/dashboard.blade.php

On the error, the event has the following structure. 
```
{type: "PusherError", data: {…}}
data: {code: 1006, message: undefined}
type: "PusherError"
__proto__: Object
```
Since we are trying to access the error key inside the event. it was throwing the undefined error.

Fix Uncaught TypeError: Cannot read property 'data' of undefined.

---

src/HttpApi/Controllers/FetchUsersController.php
src/WebSockets/Channels/PresenceChannel.php
tests/Channels/PresenceChannelTest.php
tests/HttpApi/FetchChannelTest.php
tests/HttpApi/FetchChannelsTest.php
tests/Mocks/Connection.php
tests/TestCase.php

So after #527 I noticed the counts were still wrong in my app. Dangit I thought this must be my stupid JavaScript code not counting correctly. As it turns out it was not 😄  (that does not happen often).
Pusher only fires `member_added` and `member_removed` events after the first and last socket connection for a user ID. This library would always emit a `member_added` event regardless how many times the user was already connected (same for `member_removed`). This PR aims to fix that behaviour. 
Please go over it to make sure it's correct. The tests should prove that it works, but please make sure I've interpreted the Pusher docs correctly and the tests validate the correct behaviour.
This might technically be a breaking change so not sure this could be 1.8 although it would be very nice to …

Fix presence channels emitting too much events

---

src/ChannelManagers/LocalChannelManager.php
src/ChannelManagers/RedisChannelManager.php
src/Channels/PresenceChannel.php
src/Contracts/ChannelManager.php
tests/Mocks/Connection.php
tests/PresenceChannelTest.php

Replicated the PR in the current 2.x implementation: https://github.com/beyondcode/laravel-websockets/pull/530

Presence Channels emit added or removed events more than once for same users

---

config/websockets.php
src/API/FetchChannels.php
src/ChannelManagers/LocalChannelManager.php
src/ChannelManagers/RedisChannelManager.php
src/Channels/Channel.php
src/Channels/PresenceChannel.php
src/Channels/PrivateChannel.php
src/Contracts/ChannelManager.php
src/Helpers.php
src/Server/Messages/PusherChannelProtocolMessage.php
src/Server/WebSocketHandler.php
src/Statistics/Collectors/MemoryCollector.php
tests/Mocks/PromiseResolver.php
tests/TestCase.php

I assume some errors caused by the presence channel users list is because the promises are running all at the same time and they don't get time to finish previous tasks (like putting the users in Redis then retrieving them later when joining the presence channel)
This PR adds support for channel manager's functions to always return promises so that during the business logic in controllers and handlers, they will be executed in order.

[2.x] Ensure promises run one-after-another

---

docs/advanced-usage/dispatched-events.md
docs/advanced-usage/non-blocking-queue-driver.md
docs/horizontal-scaling/redis.md
src/Channels/Channel.php
src/Channels/PresenceChannel.php
src/Events/ConnectionClosed.php
src/Events/ConnectionPonged.php
src/Events/NewConnection.php
src/Events/SubscribedToChannel.php
src/Events/UnsubscribedFromChannel.php
src/Events/WebSocketMessageReceived.php
src/Server/Messages/PusherChannelProtocolMessage.php
src/Server/WebSocketHandler.php

Added events dispatch on various actions throughout the server (like new connections, channel subscriptions, etc.) that can be easily handled by the Laravel events observers outside the server, now that the async queue driver exists and can be used for listeners to avoid any blocking I/O.

[2.x] Dispatch events on actions

---

composer.json
src/Console/StartWebSocketServer.php
src/Statistics/Logger/HttpStatisticsLogger.php
tests/TestCase.php

[fix/1.x] Replace react-buzz with react-http

---

src/WebSocketsServiceProvider.php

Queue is already aliased as the facade Queue, which makes it look for Illuminate\Support\Facades\Queue\AsyncRedisConnector

Fix conflicting namespace with facade

---

src/ChannelManagers/RedisChannelManager.php

Key ".modes" was missing, always making it default

Fix wrong redis replication connection config path

---

src/Contracts/StatisticsCollector.php
src/Statistics/Collectors/MemoryCollector.php
src/Statistics/Collectors/RedisCollector.php
src/Statistics/Statistic.php
tests/PresenceChannelTest.php
tests/StatisticsStoreTest.php

This PR will be addressed to any stale data that was previously found on production environments, as well as the ones related to stale data still present in Redis, like https://github.com/beyondcode/laravel-websockets/issues/508#issuecomment-713548902
Trace resetting is a way of saying "do not store an array key in-memory/in-database for this app because no activity was recently found". Trace resetting will take care to stop making data points if there was no activity, instead of making data points with 0 values.
Stale data is being present because of the hard shutdowns of the app. If there are any connections that get hard deleted without being able to close all the connections in a soft manner, we can end up with stored members into Redis, but without active connections existent.
Also: …

[fix] Fix stale data

---

config/websockets.php
src/WebSocketsServiceProvider.php

This PR adds an option to customize dashboard domain and path (prefix) using environment variables, similar to Telescope or Horizon.

[2.x] Customize dashboard domain and path using env vars

---

src/Statistics/Http/Middleware/Authorize.php
tests/Statistics/Controllers/WebSocketsStatisticsControllerTest.php

It does better by searching for a key instead of a secret.
Closes #622

[fix] Check for key app on authorization

---

src/ChannelManagers/LocalChannelManager.php

hi,
while debugging the stale connections issue i found this bug:
https://github.com/beyondcode/laravel-websockets/blob/11630783282eb0a189ea4ff902574b3d195f2ac9/src/ChannelManagers/LocalChannelManager.php#L454
is never successfull as 
https://github.com/beyondcode/laravel-websockets/blob/11630783282eb0a189ea4ff902574b3d195f2ac9/src/ChannelManagers/LocalChannelManager.php#L537
always returns a _new_ random owner and `release` won't allow this, so line 454 needs the fix

fix never releasing lock

---

composer.json
src/HttpApi/Controllers/TriggerEventController.php

This package is almost compatible with php-pusher 5.x out of the box.
5.x expects a empty repsonse, or a response containing channel information (Expirimental) (See pusher docs: https://pusher.com/docs/channels/library_auth_reference/rest-api#successful-response)
This change looks to be backwards compatible with 4.x since the old php-pusher package didn't do anything with the responded data.

[1.x] Add support for php-pusher 5.x

---

.github/workflows/run-tests.yml
composer.json

I would like to at least test and see if PHP 8.0 would work with the existing codebase.
This is for the issue #639 about PHP 8.0. It is mentioned there that 2.x will have PHP 8.0 support, but it's only in beta and has been so for at least 5 months. Also having to upgrade to it means having to deal with potentially breaking changes which don't even seem to be listed anywhere, assuming there are breaking changes.
Also there was a PR for PHP 8.0 support for version 1.x (#659), but unlike there, here I make the change to the CI config as well to test in PHP 8.0.

Support and test PHP 8.0

---

src/Console/Commands/StartServer.php
src/WebSocketsServiceProvider.php

Small change to singleton management that'll be needed in order to run this package with Octane.

[2.x] Laravel Octane support

---

src/Console/StartWebSocketServer.php
src/WebSocketsServiceProvider.php

Mirroring breaking change fixes for Laravel Octane (https://github.com/beyondcode/laravel-websockets/pull/733)

[1.x] Laravel Octane fixes

---

docs/advanced-usage/custom-websocket-handlers.md
src/Console/Commands/StartServer.php
src/Server/Router.php
tests/Handlers/TestHandler.php
tests/TestCase.php

Closes #731 #660
Registering custom websocket handlers can now be done like this:
```php
WebSocketsRouter::addCustomRoute('GET', '/my-websocket', \App\MyCustomWebSocketHandler::class);
```

[2.x] Fix Websocket Handlers registration

---

composer.json

Looks like you missed ^ symbol in illuminate/console dependancy

[2.x] Seems like typo in composer.json

---

composer.json

This dependency isn't required since Testbench 3.6

Remove `orchestra/database`

---

docs/basic-usage/ssl.md

Not sure which doc branch is deployed currently but this should also be merged to master probably.
Could save some hours of debugging if you don't notice the missing port in the failed websocket connection URL.

Fix missing `wssPort` for SSL example

---

composer.json

` Problem 1
- beyondcode/laravel-websockets[1.12.0, ..., 1.x-dev] require guzzlehttp/psr7 ^1.5 -> found guzzlehttp/psr7[1.5.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
- Root composer.json requires beyondcode/laravel-websockets ^1.12 -> satisfiable by beyondcode/laravel-websockets[1.12.0, 1.x-dev].
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

guzzlehttp/psr7  2.0 support

---

composer.json

Allow for pusher-php-server versions 6 and 7

Update composer.json to allow for latest Pusher version

---

composer.json

`doctrine/dbal` was added in https://github.com/beyondcode/laravel-websockets/commit/375078e686a2374cf1aebd16a394e0044cf15f24
The dependency is only necessary if you intend to run [database/migrations/0000_00_00_000000_rename_statistics_counters.php](https://github.com/beyondcode/laravel-websockets/blob/master/database/migrations/0000_00_00_000000_rename_statistics_counters.php)
This mimics the behavior of [laravel/framework](https://github.com/laravel/framework/blob/8.x/composer.json#L137)
Closes #883

Move doctrine/dbal to suggests

---

tests/FetchChannelTest.php
tests/FetchChannelsTest.php
tests/FetchUsersTest.php
tests/PresenceChannelTest.php
tests/PrivateChannelTest.php
tests/PublicChannelTest.php
tests/TestCase.php
tests/TriggerEventTest.php

https://github.com/beyondcode/laravel-websockets/pull/885#issuecomment-982707860
>from V6 build_auth_query_string change for build_auth_query_params, tests must be fixed
@mpociot fix breaking changes on tests with latest pusher versions, bug introduced on #885

Fix tests for Pusher V6 and V7

---

src/HttpApi/Controllers/Controller.php

Linked issue: [https://github.com/beyondcode/laravel-websockets/issues/865](https://github.com/beyondcode/laravel-websockets/issues/865)

patch: Content-Length header on connection and error responses

---

.github/workflows/ci.yml
composer.json
src/API/Controller.php
src/Dashboard/Http/Controllers/SendMessage.php
src/Server/HealthHandler.php

Support `PHP 8.1`
Fix `guzzlehttp/psr7`

Tests fixes(PHP 8.1, guzzlehttp/psr7)

---

src/API/Controller.php

Hi there,
Thanks for all the hard work on this awesome package!
`JsonReponse::create` is now deprecated. This PR fixes that method call in `sendAndClose` so this will work with Laravel 9.

Fix call to deprecated JsonResponse::create()

---

src/HttpApi/Controllers/Controller.php

From #942 – This is the update for the 1.x branch.
Thanks Marcel!

[1.x] Fix call to deprecated JsonResponse::create()

---

src/Dashboard/DashboardLogger.php

Fix `PHP Deprecated:  Function strftime() is deprecated in .../src/Dashboard/DashboardLogger.php on line 88`

[1.x] fix PHP 8.1 deprecation notice

---

.github/workflows/run-tests.yml
composer.json
src/HttpApi/Controllers/Controller.php
src/Statistics/Logger/HttpStatisticsLogger.php
tests/HttpApi/FetchChannelTest.php
tests/HttpApi/FetchChannelsTest.php
tests/HttpApi/FetchUsersTest.php
tests/TestCase.php

Hi there,
This PR updates the versions for pusher-php-server to match the master branch. In Laravel 9 I believe you need to use version ^7.0.
- This will make the 1.x version useable in Laravel 9.
- All of these changes are already reflected in the master branch
Fixes #951 
Fixes #956
Fixes #945 
Fixes #943

[1.x] Update pusher/pusher-php-server versions

---

src/HttpApi/Controllers/TriggerEventController.php

This is just a backport of a small part of commit fb958fb851
It should fix #1041.
The same issue is also reported in pusher/pusher-http-php#351.

Make TriggerEventController accept both 'channel' and 'channels'.

---

src/HttpApi/Controllers/TriggerEventController.php

Should fix #1146 that is caused by Symfony deprecating non-scalar values in InputBag.php.

Fix Symfony deprecation error in TriggerEventController
